# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Weather Network' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Weather Network
  pod 'OpenWeatherMapAPI', '~> 0.0.5'
  pod 'SVProgressHUD'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GHODictionary'
  pod 'TSMessages'
  pod 'JSONModel'

  target 'Weather NetworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Weather NetworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
